swagger: "2.0"
info:
  description: "Documentación de los servicios de la Banca Genérica  " 
  version: "0.1.0"
  title: "Middleware"
host: "200.39.24.141"
basePath: "/"

paths:

  
  /recoverFiles:
    post:
      tags:
      - "Nomina"
      summary: "Logs user into the system"
      description: ""
      operationId: "recoverFiles"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/recoverFiles"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/responseRecoverFiles"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"

  /user/login:
    post:
      tags:
      - "User"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/Client"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/success"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"

  /user/key:
    post:
      tags:
      - "User"
      summary: "Dinamic Key"
      description: ""
      operationId: "dinamicKey"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/key"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/keySuccess"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"


  /nomina/filter:
    post:
      tags:
      - "Nomina"
      summary: "/nomina"
      description: "Servicio que realiza la busqueda de layouts por el parametro type."
      operationId: "filter"
      parameters:
      - in: "body"
        name: "type"
        description: "Parametro de busqueda en la base de datos de layouts"
        required: true
        schema:
          $ref: "#/definitions/SearchLayoutByType-in"
      responses:
        200:
          description: "Resultado de busqueda por parametro type"
          schema:
              $ref: "#/definitions/SearchLayoutByType-res"
        default:
          description: "No hay resultados de layouts para la busqueda realizada"
          schema:
              $ref: "#/definitions/EmptyArray"
          
      x-swagger-router-controller: "Filter"


  
  /nomina/getConfLayout:
    post:
      tags:
      - "Nomina"
      summary: "/nomina"
      description: "Servicio que realiza una consulta de los diferentes layout de nomina."
      operationId: "layout"
      parameters:
      - in: "body"
        name: "Existe layout"
        description: "layout"
        required: true
        schema:
          $ref: "#/definitions/FileDefinition-in"
      responses:
        200:
          description: "Validacion de layout"
          schema:
              $ref: "#/definitions/FileDefinition-res"
        default:
          description: "layout no existe"
          schema:
            $ref: "#/definitions/Errorlayout"
      x-swagger-router-controller: "Nomina"

  /facultamiento/menu:
    post:
      tags:
      - "Facultamiento"
      summary: "/menu"
      description: "menu bancanet"
      operationId: "menu"
      parameters:
      - in: "body"
        name: "menu"
        description: "Consulta menu por usuario"
        required: true
        schema:
          $ref: "#/definitions/menu-in"
      responses:
        200:
          description: "responde menu"
          schema:
            $ref: "#/definitions/inline_response_200"
        403:
          description: "Cliente no encontrado"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Facultamiento" 

  /nomina/saveFile:
    post:
      tags:
        - "Nomina"
      operationId: "sendLayout"
      summary: "/nomina"
      description: ''
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: id
          in: header
          description: 'El id es el identificador  del layout que el servicio va validar'
          required: false
          type: integer

        - name: file
          in: formData
          description: 'file es el form-data que consume un archivo con .zip el cual contiene el archivo txt con las transacciones'
          required: true
          type: file
      responses:
          '200':
            description: 'Valida la estructura del archivo que se adjunta'
            schema:
              $ref: '#/definitions/customModels'
      x-swagger-router-controller: "Nomina"



definitions:


  recoverFiles:
    type: "object"
    properties:
      client:
        type: "string"
        example: "banco"
      type:
        type: "string"
        example: "Nómina"
      subType:
        type: "string"
        example: "Multiva"
  responseRecoverFiles:
    type: "array"
    items:
            $ref: "#/definitions/responseRecoverFiles2"
  responseRecoverFiles2:
    properties:
        fileName:
            type: "string"
            example: "nomina150115"
        date:
            type: "string"
            example: "060617"
        identificator:
            type: "string"
            example: "1"
        description:
            type: "string"
            example: "Pago por Rutina"
        numberRecords:
            type: "string"
            example: "8"
        

  SearchLayoutByType-in:
    properties:
      type:
        type: "string"
        example: "Nómina"

  SearchLayoutByType-res:
    type: "array"
    items:
      $ref: "#/definitions/SampleSearchByType"

  SampleSearchByType:
    properties:
      type:
         type: string
         example: "Nómina"
      subtype:
        type: string
        example: "SubTypeNómina"
      idFileType:
        type: integer
        example: 1
        
  EmptyArray:
    type: "array"
    items: {}
    example: []
  
  


  Client:
    type: "object"
    properties:
      Client:
        type: "string"
        example: "Cliente1"
      Password:
        type: "string"
        example: "12345678"
  success:
    type: "object"
    properties:
        status:
            type: integer
            example: integer
  key:
    type: "object"
    properties:
        dinamicKey:
            type: "string"
            example: "123456"
  keySuccess:
    type: "object"
    properties:
        status:
            type: integer
            example: integer
  
  
  
  
  
  

  FileDefinition-in:
    properties:
      idFileType:
        type: "integer"
        example: 1
  FileDefinition-res:
    properties:
      idFileType:
        type: "integer"
        example: 1
      fileType:
        type: "string"
        example: "layout 'C' formatos para importación (TEF / TEF Intelar)"
      type:
        type: "string"
        example: "Nómina"
      subtype:
        type: "string"
        example: "NóminaSubType"
      validationSide:
        type: "integer"
        example: 3
      keyLen:
        type: "integer"
        example: 2
      lines:
        $ref: "#/definitions/lines"

  customModels:
    properties:
      descripción:
         type: string
         example: "Se procesaron el siguiente numero de transacciones correctamente."



  lines:
    properties:
      99:
        $ref: "#/definitions/99"
      OO:
        $ref: "#/definitions/OO"
      O1:
        $ref: "#/definitions/OO"
  99:
    required:
    - "len"
    - "appears"
    properties:
      appears:
        type: "string"
        example: 1
      len:
        type: "integer"
        example: 52
      fields:
        type: "array"
        items:
          $ref: "#/definitions/fields"
  OO:
    required:
    - "len"
    - "appears"
    properties:
      appears:
        type: "boolean"
        example: true
      len:
        type: "integer"
        example: 1
      fieldFields:
        type: "array"
        items:
          $ref: "#/definitions/fields"

  fields:
    properties:
      name:
        type: "string"
        example: "tipoRegistro"
      len:
        type: "integer"
        example: 1
      start:
        type: "integer"
        example: 0
      type:
        type: "integer"
        example: "int"
      validations:
        type: "array"
        items:
          $ref: "#/definitions/validations"
  validations:
    properties:
      validationSide:
        type: "integer"
        example: 3
      rule:
        type: "string"
        example: "footerEqualTo"
      params:
        type: "array"
        items:
          $ref: "#/definitions/params"
  params:
    properties:
      value:
        type: string
        example: 4


  menu-in:
    properties:
      id:
        type: "integer"
        example: 1
    description: "Valores de regreso de clave dinamica"
  #//////////////////////////////////////////////////////////////////////////////////////////////////// 
  inline_response_200:
    properties:
      id:
        type: "integer"
        example: 1
      Menu:
        $ref: "#/definitions/menu"        
    description: "Valores de regreso de clave dinamica"  

  menu:
    properties:
      id:
        type: "string"
        example: "01"
      name:
        type: "string"
        example: "CONSULTAS"
      componet:
        type: "string"
        example: ""       
      submenu:
        type: "array"
        items:
         $ref: "#/definitions/submenu"         
   
  submenu:
    properties:
    
      id:
        type: "string"
        example: "0102"
      name:
        type: "string"
        example: "Estados de cuenta"
      componet:
        type: "string"
        example: ""   
      submenu:
        type: "array"
        items:
          $ref: "#/definitions/subsubmenu"          
      
  subsubmenu:
    properties:
    
      id:
        type: "string"
        example: "010201"
      name:
        type: "string"
        example: "En linea"
      componet:
        type: "string"
        example: ""  

  Error:
    properties:
      Error:
        type: "string"
        example: "Error en la autenticacion"
        description: "Respuesta de Login"
    description: "Error de Respuesta dinamica"
  Errorlayout:
    properties:
      Error:
        type: "string"
        example: "Error"
        description: "Error"
    description: "Error de Respuesta dinamica"
